<?php
require_once 'Page.php';
class PosterShop extends Page
{
    protected function __construct()
    {
        parent::__construct();
    }

    public function __destruct()
    {
        parent::__destruct(); // TODO: Change the autogenerated stub
    }

    protected function getViewData() : array {
        $sqlGet = "SELECT datei FROM poster";

        $recordSet = $this->db->query($sqlGet);

        if(!$recordSet) {
            throw new Exception("Fehler in der Datenbank: ".$this->db->error);
        }

        $result = array();

        $record = $recordSet->fetch_assoc();

        while ($record){
            $result[] = $record;
            $record = $recordSet->fetch_assoc();
        }

        $recordSet->free();

        return $result;
    }

    protected function generateView() : void {

        $this->generatePageHeader("PosterShop");
        $bildLink = $_SESSION["zimmer"];

        $posters = $this->getViewData();

        $posterOptions = "";

        foreach ($posters as $poster) {
            $posterOptions .= <<< EOT
            <option>{$poster['datei']}</option>
EOT;
        }

        echo <<< EOT
        <body onload="start();">
        <h1>Finde das passende Poster</h1>
        <div id="imgDiv">
        <img src=$bildLink alt="hintergrundbild" id="zimmer">
        <img src="" alt="poster" id="poster">
        </div>
        <br>
        <form action="PosterShop.php" method="post" accept-charset="utf-8">
        <select name="posters" id="posters" hidden>
        $posterOptions
        </select>
        <input type="button" value="Nächstes Poster" name="next" onclick="nextPoster()">
        <input type="submit" value="Poster bestellen" name="order">
        </form>
        </body>
EOT;
        $this->generatePageFooter();
    }

    protected function processReceivedData() : void {
        session_start();
        parent::processReceivedData();
        if(isset($_POST["order"])) {
            $kunde = $this->db->real_escape_string($_SESSION['kunde']);
            $datei = $this->db->real_escape_string($_POST["posters"]);
            $sqlInsert = "INSERT INTO bestellung(kunde, datei) VALUES ('$kunde', '$datei')";

            $sqlCheck = $this->db->query($sqlInsert);
            if(!$sqlCheck) {
                throw new Exception("Datenbank Fehler: ".$this->db->error);
            }
        }
    }

    public static function main()
    {
        try {
            $page = new PosterShop();
            $page->processReceivedData();
            $page->generateView();
        }
        catch (Exception $e) {
            header("Content-type:text/plain; charset=UTF-8");
            echo $e->getMessage();
        }
    }
}
PosterShop::main();
